debug: true
server:
  port: 8680
  display-name: join-wb
  pkg-name: tpltest20190612
wb:
  prefix: tpl0612
  redis:
    prefix: 02000
spring:
  application:
    name: wb
  datasource:
    names: business,plat
    business:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tl3d_cyc?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      max-active: 1
      initial-size: 1
      min-idle: 1
    plat:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tl3d_cyc?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      max-active: 1
      initial-size: 1
      min-idle: 1
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）-1
    pool.max-wait: 100
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 200
mybatis:
  configuration:
    map-underscore-to-camel-case: true 
redis:
  default:
    expire: 60
  weixin:
    expire: 86400
  activity:
    info:
      expire: 36000
  app:
    #游戏缓存过期10小时，单位s
    expire: 36000
  wxApp:
    #公众号配置过期200小时，单位s
    expire: 720000
  # 用户绑定关系缓存5分钟
  coreUserOpen: 300
    
#logging:
#  httpLogging: NONE

logging:
  path: logs/wb
  level: INFO
  cyou:
    level: DEBUG
    mapperLevel: DEBUG
    additivity: true
  httpLogging: BASIC
  logstash:
    host: 127.0.0.1
    posrt: 8888
joinactivity-wechat:
  apps:
    domain: jjjj.callback.changyou.com